version: '2'

services:
  dotnetexample:
    image: dotnetexample
    build:
      context: ./DotNetExample
      dockerfile: Dockerfile
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes